"""Identidad visible de la aplicacion."""

APPLICATION_NAME = "BITS"
APPLICATION_DISPLAY_NAME = "BITS"
APPLICATION_SHORT_NAME = "BITS"
APPLICATION_EXECUTABLE_NAME = "BITS"
APPLICATION_USER_MODEL_PREFIX = "BITS.ClasificacionBitacoras"
